### ISSUE TITLE
No Linux releases

### ISSUE THREAD

**Issue by augustjanse** [wez/atomicparsley#22]
README says to download `AtomicParsleyLinux.zip`, but there is no such file.

**Comment by miraclx** [comment]
Yeah, there hasn't been a new tagged release since the infrastructure for building those packages was set up.

In the meantime, you can get the latest release from here

https://github.com/miraclx/atomicparsley/releases/tag/20_test_alpine_release

Which is the fork whose PR added that change. (#18)

**Comment by augustjanse** [comment]
Oh, thanks for the quick response! Leaving the issue open in case you want to add a note of this somewhere/actually add new releases to this repo.

**Comment by wez** [comment]
I just tagged master as:
https://github.com/wez/atomicparsley/releases/tag/20210124.204813.840499f
