### ISSUE TITLE
Please change the cmake_minimum_required from VERSION 3.17 to VERSION 3.16

### ISSUE THREAD

**Issue by sebma** [wez/atomicparsley#34]
Hi,
To enable people using Ubuntu 20.04 (current LTS) to build `atomicparsley`, can you please change the cmake_minimum_required from VERSION 3.17 to VERSION 3.16 in your [CMakeLists.txt](../blob/master/CMakeLists.txt#L1) ?

**Comment by sebma** [comment]
@wez Hi, do you have some simple tutorial to do a PR ?

**Comment by wez** [comment]
@sebma you can click on the "edit this file" icon on https://github.com/wez/atomicparsley/blob/master/CMakeLists.txt to submit the change and we can see if it continues to build.

![image](https://user-images.githubusercontent.com/117777/125856972-3c3211ed-785b-4537-93f1-71ebdef37ea9.png)

**Comment by sebma** [comment]
@wez Thanks a lot.

I've never done a PR before. I didn't' know this could be done completely from the github gui.

**Comment by sebma** [comment]
@wez Done. They are no checks done yet in my PR ../pull/35, is this normal ?

Is it done automatically at some time of the night ?

**Comment by wez** [comment]
For security purposes, GH require approval to run PRs from new contributors, so I had to click a button!

**Comment by sebma** [comment]
@wez Thanks. Now I get a [Greatings check pb.(https://github.com/wez/atomicparsley/pull/35/checks?check_run_id=3081108642), how can I solve this ?

**Comment by wez** [comment]
> @wez Thanks. Now I get a [Greatings check pb.](https://github.com/wez/atomicparsley/pull/35/checks?check_run_id=3081108642), how can I solve this ?

Don't worry about that: it looks like the thing that auto-comments on new issues and PRs isn't working properly any more, but it isn't related to your change.

I've merged in your PR: thank you for taking the time to work through it!

**Comment by wez** [comment]
I'll tag a new release that includes that change when I'm done with work

**Comment by sebma** [comment]
@wez Thanks a lot ! Thanks to you I'm starting to understand the PR process a little.

So I want to things step by step the next time, before creating a PR I have to : 

1. Fork a project to my GitHub page
2. Create a new branch
3. Modify some files
4. Build
5. Test
5. Commit those files to my corresponding newly forked github page
6. Finally, create Create a pull request

Is that correct ?

As Inspector Columbo would say "There's still one more little detail that's bothering me" : 

Do I have to create a new branch per new issue I want to fix or per new repository or per something else ?

**Comment by wez** [comment]
Columbo is my favorite detective :-)

Yeah, that's the process.  The best practice is to have one branch per PR and to try to avoid making dependent PRs (where one PR is built on top of another PR), because unless you are a true git wizard it's really easy to screw up your repo trying to amend in review feedback across the PRs.

**Comment by wez** [comment]
I tagged https://github.com/wez/atomicparsley/releases/tag/20210715.151551.e7ad03a which includes your change

**Comment by sebma** [comment]
@wez Thanks :+1: 

Columbo is also my favorite detective. I think you might enjoy this little playlist I found on Youtube : https://www.youtube.com/playlist?list=PLpEUDnkubj7e38Iz9RzXo60Ay6xyp3adw
