### ISSUE TITLE
Atomicparsley fails with files larger than 4GB.

### ISSUE THREAD

**Issue by sheepwng** [wez/atomicparsley#42]
I'm using Windows 10 64-bit.
AtomicParsley fails with files larger than 4GB.
I searched for another fork but couldn't find an AtomicParsley that supports more than 4GB.
Previously there was a corresponding AtomicParsley in bitbucket.

https://bitbucket.org/shield007/atomicparsley

**Comment by eladkarako** [comment]
are you working directly on a sd-card or storage formatted with FAT32 by any chance?

**Comment by sheepwng** [comment]
It was a problem on the youtube-dl side.
