### ISSUE TITLE
[suggestion] manifest, versioninfo, icon for Windows OS

### ISSUE THREAD

**Issue by eladkarako** [wez/atomicparsley#43]
thanks for maintaining this project.

<img width="128" alt="128" src="https://user-images.githubusercontent.com/415238/135458918-72a10461-f032-46cf-ab22-6f4a2bda1880.png" />  

Hi, I've made a simple logo, <a href="https://docs.microsoft.com/en-us/windows/win32/menurc/versioninfo-resource">versioninfo</a>, and manifest for the Windows version,  
it helps it look more appealing and safe since it includes some information that can be seen on mouse hover and properties. those are resources that are embedded into the exe, I've used <a href="http://www.angusj.com/resourcehacker/">ResourceHacker</a> to patch the exe on <a href="https://github.com/wez/atomicparsley/releases/tag/20210715.151551.e7ad03a">20210715.151551.e7ad03a</a> release.

the manifest included in the exe was fine but it was missing a compatibility segment to help Windows 10 run it, not in a vista virtualization mode such as any exe that lacks that part:  

```xml
<compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1"> 
  <application> 
    <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}" /> 
    <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}" /> 
    <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}" /> 
    <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}" /> 
    <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}" /> 
  </application> 
</compatibility> 
```

the versioninfo resource takes-care of presenting some information of the exe in the Windows shell: 
<img width="546" alt="2021-09-30_154849" src="https://user-images.githubusercontent.com/415238/135460466-470732d2-8d2f-4d95-812c-932b86a419fe.png" />  
<img width="361" alt="2021-09-30_154923" src="https://user-images.githubusercontent.com/415238/135460487-ad42fa2c-2c21-47c9-894d-3f7688f2d03e.png" />  
<img src="https://user-images.githubusercontent.com/415238/135460552-c907fbe6-4d7b-41bc-9898-1508e4a373ed.gif" />  

<hr/>

and the icon is just for fun.

here are the graphics for the logo (png, vector, and ico)
<a href="https://github.com/wez/atomicparsley/files/7259710/graphics.zip" download="graphics.zip">graphics.zip</a>.
<pre>
+---transparent
|   +---icon
|   |       icon.ico
|   |       
|   +---png
|   |       128.png
|   |       256.png
|   |       32.png
|   |       48.png
|   |       512.png
|   |       64.png
|   |       72.png
|   |       96.png
|   |       
|   \---vector
|           vector.ai
|           vector.dxf
|           vector.emf
|           vector.eps
|           vector.ico
|           vector.pdf
|           vector.svg
|           
\---white
    +---icon
    |       icon.ico
    |       
    +---png
    |       128.png
    |       256.png
    |       32.png
    |       48.png
    |       512.png
    |       64.png
    |       72.png
    |       96.png
    |       
    \---vector
            vector.ai
            vector.dxf
            vector.emf
            vector.eps
            vector.pdf
            vector.svg
</pre>

it contains a transparent background and a white background variations.
<img width="198" alt="transparent vs white" src="https://user-images.githubusercontent.com/415238/135461332-18a3edf8-c0aa-4968-9d51-cbe5dd580f8b.png" />  

the icon contains a reduced amount of 32bit images to avoid adding too much weight to the exe.
<img width="64" alt="icon content" src="https://user-images.githubusercontent.com/415238/135461471-913b1b84-e836-44ca-a839-2321d75ed899.png">

<hr/>

to embed it yourself into the build process you can use this rc (non-compiled resources):  
[rc.zip](https://github.com/wez/atomicparsley/files/7259730/rc.zip)

<img width="921" alt="rc" src="https://user-images.githubusercontent.com/415238/135461613-d98cd83e-f844-4916-9037-93862caf7130.png" />  

or this res file (a compiled resource) that can be applied into a exe using any resource-editor (linux can use windows emulator to launch resourcehacker, for example).

[res (an already compiled rc).zip](https://github.com/wez/atomicparsley/files/7259751/res.an.already.compiled.rc.zip)

<hr/>

here is an already patched exe, 
[AtomicParsley.exe_20210715.151551.e7ad03a.0_patched_icon_versioninfo_manifest.zip](https://github.com/wez/atomicparsley/files/7259780/AtomicParsley.exe_20210715.151551.e7ad03a.0_patched_icon_versioninfo_manifest.zip)

the version info resource contains the version <code>20210715.151551.242929722.0</code>,  
the last part is the decimal of the hex <code>0xe7ad03a</code>, since hex is not compatible in version scheme. 
(I've used the browser's developer panel console to convert it using <code>console.log( parseInt("0xe7ad03a") );</code>).

<hr/>
notes:  
you can use everything in here no credit needed.
I've applied the generic manifest from [this manifest project](https://github.com/eladkarako/manifest) project.
here is an old c++ project that uses RC to embed the icon and version info too (don't use that old manifest though): [gcc-manifest-icon](https://github.com/eladkarako/gcc-manifest-icon)

notes2:
RC, manifest, txt files in the project needs to be Windows-EOL (\r\n) not linux EOL. that's just for compatibility (they would probably work either way though..)

<hr/>

**Comment by wez** [comment]
This looks good! Would you like to submit a pull request to integrate these into the build?
I don't have a lot of time for this sort of thing these days!

**Comment by eladkarako** [comment]
same here.. I wrote a quick fix for YouTube-DL with AtomicParsley,  
and got pleasantly sidetrack'ed with graphic design.. :]
anyway, everything is conveniently attached in zip files here,  
so you may close it for now, and if I'll manage to get around for a pull request, I know where to find it all :]
