### ISSUE TITLE
Suspect Writing Cast/Crew Atom is Broken

### ISSUE THREAD

**Issue by im-L0r3** [wez/atomicparsley#59]
--rDNSatom "MY CAST AND CREW XML HERE" name=iTunMOVI domain=com.apple.iTunes

In older versions of AtomicParsley Mac (AtomicParsley_0.9.5.zip) writing this worked for me.

It doesnt seem to be writing the atom at all now.

Iv very carefully checked the XML I used to embed vs what Im trying to do now and the format is correct. 

I used another tool to verify that its not being written to file (all my other atoms do write correctly)

Specifically Im attempting the following, that looks identical to what I did with the older Atomic:
Eh... even in a code block it wont render here, so screenshot...
<img width="826" alt="Screen Shot 2022-06-24 at 10 25 54 AM" src="https://user-images.githubusercontent.com/31595446/175611850-f63a5eb4-5d3b-401e-98bc-33ba00466cd3.png">

**Comment by miraclx** [comment]
That's odd. Shouldn't you contain it in a string?

`--rDNSatom "<!DOCTYPE plist PUBLIC ...>" name=iTunMOVI domain=com.apple.iTunes`

Also, include the console output of what happens when you run it.

**Comment by im-L0r3** [comment]
> That's odd. Shouldn't you contain it in a string?

Yes you are correct, this was just one example of iterations I was attempting.

I solved it today. Atomic is working properly. There was a sneaky sed removing a space changing what should have been "plist version" into "plistversion".
