### ISSUE TITLE
Como posso obter o token do Apple music??

### ISSUE THREAD

**Issue by WellingtonMonteiro** [wez/atomicparsley#8]
[•] Identifying service...[Apple Music]
  [•] Checking authentication...[authenticated]
  Detected [album]
  Obtaining album metadata...(failed: [Unexpected end of JSON input])
  [i] An error occurred while processing the query
 ========== Stats ==========
  [•] Runtime: [788ms]                                       [•] Total queries: [01]
  [•] Total tracks: [00]
      » Skipped: [00]
      ✓ Passed:  [00]
      ✕ Failed:  [00]
  [•] Output directory: [.]
  [•] Cover Art: cover.png (640x640)
  [•] Total Output size: 0.00 B                              [•] Total Network Usage: 0.00 B
      ♫ Media: 0.00 B
      ➤ Album Art: 0.00 B
  [•] Output bitrate: 320k

**Comment by adrianmejiam** [comment]
OtotoyPy not work for any albums....  only personal payment collection.

![image](https://user-images.githubusercontent.com/51228667/97602291-bf66a800-19d0-11eb-9145-9dac6b125377.png)

**Comment by wez** [comment]
Neither of the things in this issue are atomicparsley
