### ISSUE TITLE
Version Number is not reported when installed via `brew`

### ISSUE THREAD

**Issue by arejay73** [wez/atomicparsley#9]
I have updated AtomicParsley via homebrew atomicparsley 20200701.154658.b0d6223.

When I run command AtomicParsley without and parameters the version string reported is:
`AtomicParsley version:   (utf8)`

Any more script that was using this cannot read the version number to validate.  I was expecting some pattern like 0.9.6 to read.

**Comment by wez** [comment]
The version number is included when built from the git repo, and is included in the binaries available from the official release downloads.

Homebrew's recipe doesn't build from the git repo so it doesn't have any version information available to it.

**Comment by wez** [comment]
I have no plans to work on this.

**Comment by arejay73** [comment]
Cool. No worries.  Thanks for the reply.  I'll try and replace the Homebrew one with you release bins.  Thanks.

**Comment by miraclx** [comment]
> The version number is included when built from the git repo, and is included in the binaries available from the official release downloads.
> 
> Homebrew's recipe doesn't build from the git repo so it doesn't have any version information available to it.

The packages available in the releases don't have the versions either
